### PR TITLE
96boards-tools: update srcrev

### PR DESCRIPTION
**Pull request by suihkulokki**
Update the recipe to pull latest version

### CODE REVIEW

**Comment by fboudra** [comment]
Riku Voipio commented:
Well after some testing that didn't fix the issue. Still investigating.

**Comment by suihkulokki** [comment]
No other changes to 96boards-tools is expected, so feel free to merge this.

**Review by fboudra — CHANGES_REQUESTED** [review]
let's release 0.12 then and bump it here. Because PV is 0.11 and bumping SRCREV won't be enough.

**Comment by suihkulokki** [comment]
Updated version and srcrev

**Review by fboudra — APPROVED** [review]

**Pull request merged**
