### PR TITLE
Update linux-hikey kernel to RPK 4.9-rc6 based

### PR DESCRIPTION
**Pull request by fboudra**

### CODE REVIEW

**Comment by zoltan-ongithub** [comment]
lgtm

**Comment by zoltan-ongithub** [comment]
One thing actually, I checked the Kernel and there are no OP TEE patches.

**Comment by fboudra** [comment]
you may look at the wrong tree: https://github.com/Linaro/rpk/commit/1070992036f43a5cbcafce62baee01a0109318c7

**Comment by zoltan-ongithub** [comment]
Thanks, got it.

**Pull request merged**
