### PR TITLE
Fix typo in mali450-userland_r6p0_01rel0.bb

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by fboudra** [comment]
Thanks Khem. I'm going to cherry-pick the mali typo patch. For the service, I'll prefer to get the patch merged in 96boards-tools directly and then update the recipe.

**Comment by koenkooi** [comment]
is this PR still valid?

**Comment by kraj** [comment]
@fboudra picked portion of it. The patch to 96boards tools should go into tools repo and then SRCREV be bumped.

**Comment by fboudra** [comment]
Closed with the following commits:
https://github.com/96boards/96boards-tools/commit/906d4bde05b1e2d276deebecd789b53675fd7922
https://github.com/96boards/meta-96boards/commit/e958fc479bc0387843caab4392e07eff020a57be

**Pull request closed without merging**
