### PR TITLE
Update default tune configuration based on latest OE-Core

### PR DESCRIPTION
**Pull request by ricardosalveti**
Latest OE-Core removed the arch-armv8 tune file and added a new set of tune files cortex A cores.

@kraj mind having a quick look?

### CODE REVIEW

**Comment by kraj** [comment]
LGTM

**Comment by ricardosalveti** [comment]
@fboudra qcom builds should be fixed with https://github.com/ndechesne/meta-qcom/pull/91

**Comment by ricardosalveti** [comment]
Qcom changes merged, should be fine to test this again.

**Comment by ricardosalveti** [comment]
@koenkooi mind having a look? Master is currently broken without these changes. Thanks!

**Comment by fboudra** [comment]
@rsalveti sorry, I thought it was already merged. I mixed up with another MR...

**Comment by ricardosalveti** [comment]
@fboudra no worries, thanks for merging it!

**Pull request merged**
