### PR TITLE
juno: remove support

### PR DESCRIPTION
**Pull request by jonmason**
Support for the Juno reference platform is being done in the
meta-arm-bsp layer now.  Remove support here in favor of that.

Signed-off-by: Jon Mason <jon.mason@arm.com>

### CODE REVIEW

**Comment by ndechesne** [comment]
@fboudra @mrchapp is anyone using juno in their builds, in any of our internal projects?

**Comment by mrchapp** [comment]
We are, but very far from the master branch.

**Comment by jonmason** [comment]
If you are using juno, please migrate to meta-arm-bsp.  If it is missing something, please let us know and we'll add it.

**Comment by mrchapp** [comment]
> If you are using juno, please migrate to meta-arm-bsp. If it is missing something, please let us know and we'll add it.

We are using Juno and HiKey (with optee). The thing is that we're using Sumo. :(

Once we move to Dunfell we'll add meta-arm for Juno (and see how we deal with HiKey).

**Comment by ndechesne** [comment]
ok, i am merging this change. let's see if anything breaks..

**Pull request merged**
