### PR TITLE
add recipe for ChromeDriver

### PR DESCRIPTION
**Pull request by mrchapp**
This is a temporary bbappend so that ChromeDriver is
included in our builds while this pull request is merged
in upstream meta-browser:
  https://github.com/OSSystems/meta-browser/pull/34

### CODE REVIEW

**Comment by koenkooi** [comment]
minor nit: move PACKAGES_ below do_install

**Comment by mrchapp** [comment]
Refreshed.

**Comment by fboudra** [comment]
that's probably not the right place for the bbappend. meta-96boards is a bsp layer, for boards specifics changes. Most likely it should go in meta-rpb.

**Comment by mrchapp** [comment]
Merged upstream: https://github.com/OSSystems/meta-browser/pull/34

**Comment by fboudra** [comment]
@mrchapp we still need meta-rpb changes to include chromium in our images.

**Pull request closed without merging**
