### PR TITLE
hikey-32: Added preferred providers

### PR DESCRIPTION
**Pull request by psivasubramanian**
Preferred providers for egl & gles

### CODE REVIEW

**Comment by andrey-konovalov** [comment]
Why do you need that?
The preferred egl/gles providers are set depending on MACHINE_FEATURES by this code:
https://github.com/96boards/meta-rpb/blob/master/conf/distro/include/egl.inc
And both hikey and hikey-32 have mali450 in their MACHINE_FEATURES.

Are you using a distro conf different from meta-rpb?

**Comment by psivasubramanian** [comment]
Yes, I'm using RDK distro.

**Comment by koenkooi** [comment]
These are distro settings and don't belong in a machine config

**Comment by psivasubramanian** [comment]
@koenkooi  We discussed that only DEFAULTTUNE should go to distro whereas preferred providers can exist in MACHINE layer?
@kuscsik Kindly comment.

**Pull request closed without merging**
