### PR TITLE
[rocko] Deal with OpenGL r/dependencies

### PR DESCRIPTION
**Pull request by mrchapp**

### CODE REVIEW

**Comment by fboudra** [comment]
@andrey-konovalov @petegriffin FYI

**Comment by mrchapp** [comment]
Should go without saying that I meant Rocko, not
Rocky

**Comment by fboudra** [comment]
@ndechesne @koenkooi any feedback will be appreciated on the RFC. Thanks.

**Comment by koenkooi** [comment]
This adds RDEPENDS even for builds/config where opengl is disabled

**Review by ndechesne — COMMENTED** [review]
I really don't understand this commit. without more context it looks like a bug in the mali recipe instead, that we are hiding here.

**Review by ndechesne — COMMENTED** [review]
this is the same thing as https://git.linaro.org/openembedded/meta-backports.git/commit/?h=rocko&id=573e98fec16a974e3f6ef001c2c2806e6c710984, right?

i agree that meta-backports might not be the perfect place for this patch, since it's not really a backport.. i am opened to discussing more about that. but I don't think it belongs to meta-96boards, neither..

**Review by ndechesne — COMMENTED** [review]
is that being discussed on upstream list? I think it should. Also if we were to merge something like that, then I would prefer to see a first commit that imports the original file (NO-OP) and then another that adds our changes. it's not possible to review otherwise.

**Comment by mrchapp** [comment]
The kmscube change is similar in that it adds the same patch (which wasn't in Rocko when this was committed), but the important bit is DEPENDS and RDEPENDS there.

**Comment by mrchapp** [comment]
I have not brought the rdeps change to insane.bbclass to the mailing list. Before I do that, I'd like to try more things with the way things are happening in Morty, where it doesn't fail. As you say (@ndechesne), it might be more of an issue with the Mali recipe than with the insane checks.

**Comment by mrchapp** [comment]
> This adds RDEPENDS even for builds/config where opengl is disabled

All but gst-plugins-bad have `REQUIRED_DISTRO_FEATURES += "opengl"`.

For gst-plugins-bad, it might help to have
`PACKAGECONFIG_GL_hikey ?= "${@bb.utils.contains('DISTRO_FEATURES', 'opengl', 'virtual/gles2 virtual/egl', 'libgles2 libegl', d)}"`
Have to check if that works with libgstgl-1.0.

**Comment by koenkooi** [comment]
A BSP layer shouldn't have custom copies of bbclasses, those should be in the distro layer. For the (R)DEPENDS changes, can you wrap them in a python check for 'mali450' in MACHINE_FEATURES? These changes should *only* take effect if your machine uses mali drivers, it currently makes them global, impacting other machines.

**Comment by mrchapp** [comment]
> A BSP layer shouldn't have custom copies of bbclasses, those should be in the distro layer.

Can be moved to meta-rpb.

>  For the (R)DEPENDS changes, can you wrap them in a python check for 'mali450' in MACHINE_FEATURES? These changes should only take effect if your machine uses mali drivers, it currently makes them global, impacting other machines.

I see what you mean. I introduced virtual/gbm (which seemed to me the Right Thing To Do) as being PROVIDED by Mali, but Mesa does not PROVIDE it, and adding to Mesa is yet another change. Instead, the dependency can be on virtual/egl, which goes hand in hand with libgbm. This does away with the mali450 check in MACHINE_FEATURES, as the changes only establish the correct dependencies (for Mali and Mesa cases).

**Comment by mrchapp** [comment]
Branch has been updated to only use virtual/egl (or other OpenGL libraries) but not libgbm as DEPENDencies. Build-tested against RPB X11 HiKey and Dragonboard 410c.

**Comment by ndechesne** [comment]
Are these changes still expected to be merged? they still look really awful. Hard coding RDEPENDS like that seems a really bad idea. I am sorry I haven't been able to spend more time on this issue.. but i am very skeptical.. i am sure there is an issue, but i don't like this solution. 

does this patch *require* the meta-rpb change about insane class (which i don't like very much neither..)?

**Comment by mrchapp** [comment]
Changes updated to use PACKAGECONFIG where the original packages used it. The RDEPENDS had to be added and the check for RDEPENDS in insane.bbclass had to be relied upon.

**Comment by mrchapp** [comment]
No more of this insanity.

**Pull request closed without merging**
