### PR TITLE
linux-generic-next: add PSTORE_RAM to selftests/pstore fragment

### PR DESCRIPTION
**Pull request by mrchapp**
Needed for pstore_tests:
  https://bugs.linaro.org/show_bug.cgi?id=3222

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>

### CODE REVIEW

**Comment by mrchapp** [comment]
This can be reverted once Naresh' patch reaches upstream.

**Comment by fboudra** [comment]
no, we don't apply patches on -next on purpose. It's a tracking tree and a mowing target updated every day. It will break the builds as soon as the changes are landed.
The right thing to do here is to upstream the changes and wait for them to land in -next.

**Comment by mrchapp** [comment]
Is it OK to add it simply like this? I see there is another general config added (NUMA).
```
+    # Add PSTORE_RAM
+    echo 'CONFIG_PSTORE_RAM=m' >> ${B}/.config
```

It must happen right after merging kselftest's config fragments.

**Comment by fboudra** [comment]
CONFIG_PSTORE_RAM isn't a general config or a fixup.

**Pull request closed without merging**
