### PR TITLE
 grub: drop custom recipe and migrate to the upstream grub-efi version

### PR DESCRIPTION
**Pull request by rsalveti**
Migrate to the upstream grub-efi recipe instead of maintaining a fork as that is causing conflicts with several other layers (e.g. issue #240).

### CODE REVIEW

**Comment by rsalveti** [comment]
Only tested with hikey, but it should work the same way with the other targets.

**Comment by rsalveti** [comment]
Will also propose the remaining changes upstream, but this should at least unblock the issue.

**Review by fboudra — APPROVED** [review]
LGTM

**Comment by rsalveti** [comment]
@koenkooi mind having a look? Thanks!

**Pull request merged**
