### PR TITLE
hikey: enable second console on UART0

### PR DESCRIPTION
**Pull request by mwasilew**
In order to avoid serial line interlacing during automated testing,
second serial console is enabled on UART0. The default console remains
on UART1.

Signed-off-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>

### CODE REVIEW

**Comment by fboudra** [comment]
@mwasilew on AOSP kernel, the UART1 is ttyFIQ0. Is the second serial console also ttyAMA2 on AOSP kernels?

**Comment by ndechesne** [comment]
Do we really want that by default? The uart0 can be used for other purpose.

**Comment by mwasilew** [comment]
@fboudra I didn't check aosp yet.
@ndechesne is there any other way of enabling getty on the second uart in the image for LKFT? We need that for automated testing for sure. I have no strong preference, so if there is a better way, I'm OK with that.

**Comment by ndechesne** [comment]
most probably yes. but i don't know how , OTOH. 

i made this remark because i will not merge similar patch into meta-qcom for example.. just wanted to highlight that.

**Comment by mwasilew** [comment]
@ndechesne I think I can solve this using only LAVA features. So even this PR would not be possible. I'll check that and close the PR if it works.

**Comment by fboudra** [comment]
fwiw, I don't get @ndechesne rationale about rejecting such patch and I'm happy to merge it for hikey or being LKFT specific. My only concern is the tty name when we use an AOSP kernel.

**Comment by mwasilew** [comment]
@fboudra checked on linaro-hikey (android-common) 4.9 and the ttyAMA2 is still there and the same hack works.

**Comment by ndechesne** [comment]
@fboudra my concern is that this change is done for hikey machine, every user of the hikey machine will now have 2 serial console setup, even outside of LKFT.

**Comment by fboudra** [comment]
We'll do it in LKFT only then, on selected boards.

**Pull request closed without merging**
