### PR TITLE
u-boot-juno: Remove recipe

### PR DESCRIPTION
**Pull request by kraj**
juno support has been dropped

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
@jonmason FYI

**Comment by kraj** [comment]
ping

**Comment by kraj** [comment]
CI failure https://ci.linaro.org/job/rpb-openembedded-meta-96boards-premerge-ci-master/DISTRO=rpb,MACHINE=dragonboard-410c,label=docker-buster-amd64/18/console

is unrelated

**Comment by kraj** [comment]
Can someone look into this pull please ?

**Comment by ndechesne** [comment]
I can merge.. but I should really not be the one doing that.. @fboudra , @mrchapp , can you please confirm it's ok?

**Pull request merged**
