### PR TITLE
[Poplar] Fix URIs to github repositories for u-boot and Linux.

### PR DESCRIPTION
**Pull request by clopez**
Building Yocto branch rocko for board poplar I got this errors:

```
ERROR: u-boot-poplar-v2017.09+gitAUTOINC+98469ebb7a-r0 do_fetch: Fetcher failure: Unable to find revision 98469ebb7afaacc742d6f651f8e676e755672a63 in branch latest even from upstream
ERROR: u-boot-poplar-v2017.09+gitAUTOINC+98469ebb7a-r0 do_fetch: Fetcher failure for URL: 'git://github.com/linaro/poplar-u-boot;protocol=git;branch=latest'. Unable to fetch URL from any source.
ERROR: u-boot-poplar-v2017.09+gitAUTOINC+98469ebb7a-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/igalia/clopez/yocto/poplar/build_poplar/tmp/work/poplar-poky-linux/u-boot-poplar/v2017.09+gitAUTOINC+98469ebb7a-r0/temp/log.do_fetch.46598
ERROR: Task (/home/igalia/clopez/yocto/poplar/meta-96boards/recipes-bsp/u-boot/u-boot-poplar.bb:do_fetch) failed with exit code '1'
```

```
ERROR: linux-poplar-4.9+gitAUTOINC+e153b53cbd-r0 do_fetch: Fetcher failure: Unable to find revision e153b53cbd7047d7e6863c1850dda751f4a7f333 in branch poplar-4.9 even from upstream
ERROR: linux-poplar-4.9+gitAUTOINC+e153b53cbd-r0 do_fetch: Fetcher failure for URL: 'git://github.com/Linaro/poplar-linux.git;protocol=https;branch=poplar-4.9;name=kernel'. Unable to fetch URL from any source.
ERROR: linux-poplar-4.9+gitAUTOINC+e153b53cbd-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/igalia/clopez/yocto/poplar/build_poplar/tmp/work/poplar-poky-linux/linux-poplar/4.9+gitAUTOINC+e153b53cbd-r0/temp/log.do_fetch.13069
ERROR: Task (/home/igalia/clopez/yocto/poplar/meta-96boards/recipes-kernel/linux/linux-poplar_git.bb:do_fetch) failed with exit code '1'
```

This patches fixes this.

### CODE REVIEW

**Comment by fboudra** [comment]
@petegriffin fyi

**Comment by petegriffin** [comment]
LGTM

**Comment by fboudra** [comment]
@shawnguo2 can you confirm the u-boot branch to use?

**Comment by shawnguo2** [comment]
https://github.com/96boards-poplar/u-boot latest
https://github.com/96boards-poplar/linux poplar-4.9

**Review by fboudra — CHANGES_REQUESTED** [review]
As mentioned by Shawn, it's latest branch that should be used.

**Comment by fboudra** [comment]
@shawnguo2 Thanks. @clopez Please adjust your PR accordingly. U-Boot branch should be latest instead of alex/latest.

**Comment by clopez** [comment]
> @shawnguo2 Thanks. @clopez Please adjust your PR accordingly. U-Boot branch should be latest instead of alex/latest.

Sorry, there referenced commit can only be found on the branch alex/latest

```
$ git clone https://github.com/96boards-poplar/u-boot 
[...]
$ cd u-boot
$ git branch -a
$ git branch -a
  * latest
    remotes/origin/HEAD -> origin/latest
    remotes/origin/alex/latest
    remotes/origin/latest
    remotes/origin/shawn/install
```

The referenced commit on the u-boot bitbake recipe is  98469ebb7afaacc742d6f651f8e676e755672a63 and git says this
```
$  git branch -a --contains 98469ebb7afaacc742d6f651f8e676e755672a63
   remotes/origin/alex/latest
```

**Comment by shawnguo2** [comment]
@clopez You can keep using 'alex/latest' branch with the commit in the boot recipe, but we are not going to update the branch any more.  Instead, branch 'latest' is the one we are currently maintaining and updating.  So you are suggested to update the boot recipe to use the HEAD of this branch.

**Comment by clopez** [comment]
> @clopez You can keep using 'alex/latest' branch with the commit in the boot recipe, but we are not going to update the branch any more. Instead, branch 'latest' is the one we are currently maintaining and updating. So you are suggested to update the boot recipe to use the HEAD of this branch.

That's a different history.

This patch only fixes the references to the repositories and allows Yocto to fetch those commits. With this patches It builds fine, otherwise a fetch error will happen.

But this patches doesn't update the reference commit that will be built. If you want to update the recipe to use a different commit feel free to do that in a follow-up commit. I won't do that as I can't currently test that what I have built runs ok because I don't know how to flash the built products I got. See: https://github.com/96boards-poplar/Documentation/issues/4

**Comment by fboudra** [comment]
@clopez make sense. I'd like to move to latest so I'll do a follow up commit.

**Pull request merged**
