### PR TITLE
96boards-tools: Package and init the resize-disk script

### PR DESCRIPTION
**Pull request by kraj**
Make this script run once on boot

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by fboudra** [comment]
@khem we may need to disable this feature since it forces to reboot which is a problem in automated validation (in lava for instance). what do you propose for such scenario?

**Comment by ndechesne** [comment]
don't we already have the systemd service for that? i don't understand why we are adding another one. is that for non-systemd boot?

**Comment by ndechesne** [comment]
and, also, i don't understand why we are forcing a reboot. we've been using the systemd service at boot for months now, and we never required a reboot.

**Comment by kraj** [comment]
Hmm, I added a reboot for safety, I have not seen any issues without doing a reboot. Since the resize
happens very early there is no data generated yet. so we could disable explicit call to reboot
secondly we could remove INITSCRIPT_NAME = "resize-disk" or make it ?= so it can be emptied out.

**Comment by kraj** [comment]
@ndechesne there is more than just systemd in world :)

**Comment by kraj** [comment]
I will send another pu to tools. to remove reboot call.

**Comment by ndechesne** [comment]
@kraj but i thought you were on the right side of the world, the side of systemd ;-)

**Comment by kraj** [comment]
@ndechesne I have had my revelations !!, the way systemd dissed non-glibc support and optimization for footprint, there always will be alternatives to live by e.g. small iot devices and
wifi access point pods.

**Comment by kraj** [comment]
ok here is v2. Also introduced a PV append to add dependency on SRCREV so fetcher is happy.
btw. I plan to move 96boards-tools recipe to meta-oe since it is useful beyond 96boards, hope you are ok with that.

**Comment by ndechesne** [comment]
@kraj re: moving to meta-oe, i think there is a bit of internal crap in 96boards-tools that doesn't need to be moved to meta-oe.. maybe we should split it a bit, before moving. what is it that you find useful really, beyond the resize scripts?

**Comment by kraj** [comment]
@fboudra can this be merged now ?

**Review by fboudra — APPROVED** [review]
LGTM. give a chance to @ndechesne and @koenkooi to give feedback.

**Review by koenkooi — APPROVED** [review]
LGTM as well

**Comment by kraj** [comment]
@fboudra can we merge it now that @koenkooi has approved it too

**Pull request merged**
