### PR TITLE
python3 fixes

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by petegriffin** [comment]
@kraj edk2-hikey using python3 isn't enough. It solves the parse errors, but the python scripts in edk2 don't work with the python3 interpreter.

**Comment by petegriffin** [comment]
@kraj @fboudra @ndechesne I was just looking some more at this and I think for the moment for edk2-hikey the only (easy) option is to continue to depend on meta-python2 layer. edk2 has about 1875 python scripts in the source directory.

I tried running 2to3 on them, and then some manual import fixups, but I'm still getting syntax errors. Also I'm not sure anyone cares enough about hikey now to re-do/rebase edk2 firmware onto something newer (which presumably then has migrated to a newer python) release.

**Comment by petegriffin** [comment]
or we could switch to using u-boot, and get rid of edk2 entirely :)

**Comment by kraj** [comment]
> @kraj edk2-hikey using python3 isn't enough. It solves the parse errors, but the python scripts in edk2 don't work with the python3 interpreter.

yes I knew but then that would be step2 to fix the scripts

**Pull request merged**
