### PR TITLE
linux-96boards: update to 16.06

### PR DESCRIPTION
**Pull request by koenkooi**
Signed-off-by: Koen Kooi koen.kooi@linaro.org

### CODE REVIEW

**Comment by fboudra** [comment]
unrelated to the change but I noticed the compatible machine list contains "vexpress-juno". I think it's misnamed. The versatile express product family contains Juno and the Versatile Express CoreTile boards, which we commonly call the latter vexpress. It also reflected in the dtb name. Probably something to fix in a separate commit.

**Comment by koenkooi** [comment]
I picked the name optee uses for juno, I have no preference for naming it, 'juno' would be fine by me as well. Let me know what you want and I can fix up the commit.

**Comment by fboudra** [comment]
simply "juno" then. Thanks!

**Comment by koenkooi** [comment]
done

**Pull request merged**
